### ISSUE TITLE
Add a version number to package.json

### ISSUE THREAD

**Issue by bebaps** [ASUWebPlatforms/webspark-theme-renovation#220]
# Issue

Unable to install this repo as a package via:

`npm i https://github.com/ASUWebPlatforms/webspark-theme-renovation`

# Why I want to do this

On our site, the Renovation theme will only take us so far. Custom blocks, view, templates, etc. will inevitably need to be added. Others have already begun to create their own Renovation child themes, and I was given [this one](https://github.com/travisbutterfield/customrenovation/blob/main/src/sass/customrenovation.style.scss) to use as an example. Considering how the `scss` is being pulled, this makes the workflow very specific to a certain file structure. Also, this is really just extra work as the CSS is having to be recompiled. This makes it easy for someone to introduce changes that may be off brand, or simply to forget to add a particular file. In addition to copying the Sass variables, the JS is also being reloaded.

I believe it would be much more consistent to simply have the latest release of Renovation as a dependency so that any files can be referenced from there directly, in the event that any customizations must be made. The approach I am assuming with these customizations is that the child theme adds onto Renovation, and will not intend to override Renovation.

This repo is open to the public, so the intent is already that we want to share this with others internal to ASU as well as externally. 

# Proposed Solution

Add the version key to the `package.json` (it won't hurt to add it to the `composer.json` either). Adding this will also make it easier to publish to NPM if that is in the plans.

Current:
```json
{
  "name": "renovation",
  "description": "A theme based on Radix.",
  ...
}
```

Proposed:
```json
{
  "name": "renovation",
  "description": "A theme based on Radix.",
  "version": "1.0.3",
  ...
}
```

**Comment by mlsamuelson** [comment]
Hi @duarte-daniela , do you have any thoughts about this proposed change?

**Comment by bebaps** [comment]
This has been stale for a while, but if I recall this was not something we wanted to do at this time. Closing for now.
